name: Daily Workout Email

on:
  schedule:
    - cron: '30 0 * * 0-5'
  workflow_dispatch:

jobs:
  send-workout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Generate Gradle wrapper
        run: gradle wrapper
      - name: Build with Gradle
        run: ./gradlew build
      - name: Send workout email
        run: ./gradlew run
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EWA_PASSWORD: ${{ secrets.EWA_PASSWORD }}
